/**
 * Cure Temprature App
 * Cure Temprature APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammedzaki.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface APIResponse {
    success?: boolean;
    message?: string;
    data?: any;
}
