/**
 * Cure-Temperature APIs
 * This is Cure-Temperature server. You can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammedzaki.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Device {
    /**
     * id
     */
    id?: number;
    /**
     * name
     */
    name?: string;
    /**
     * serial_number
     */
    serialNumber?: string;
    /**
     * description
     */
    description?: string;
    /**
     * temp
     */
    temp?: string;
    /**
     * percentage
     */
    percentage?: number;
    /**
     * alarm
     */
    alarm?: boolean;
    /**
     * reverse
     */
    reverse?: boolean;
    /**
     * device_category_id
     */
    deviceCategoryId?: number;
    
    shouldShow?: boolean;
}
