/**
 * Cure-Temperature APIs
 * This is Cure-Temperature server. You can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mohammedzaki.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface DeviceCategory {
    /**
     * id
     */
    id?: number;
    /**
     * name
     */
    name?: string;
    /**
     * min_temperature
     */
    minTemperature?: number;
    /**
     * max_temperature
     */
    maxTemperature?: number;
    /**
     * alarm_times
     */
    alarmTimes?: number;
    /**
     * alarm_frequency
     */
    alarmFrequency?: number;
}
